/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as HomeBuyersRouteImport } from './routes/home-buyers'
import { Route as InvestorsRouteImport } from './routes/investors'
import { Route as MortgageSolutionsRouteImport } from './routes/mortgage-solutions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeBuyersRoute = HomeBuyersRouteImport.update({
  id: '/home-buyers',
  path: '/home-buyers',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorsRoute = InvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => rootRouteImport,
} as any)
const MortgageSolutionsRoute = MortgageSolutionsRouteImport.update({
  id: '/mortgage-solutions',
  path: '/mortgage-solutions',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calculator': typeof CalculatorRoute
  '/home-buyers': typeof HomeBuyersRoute
  '/investors': typeof InvestorsRoute
  '/mortgage-solutions': typeof MortgageSolutionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calculator': typeof CalculatorRoute
  '/home-buyers': typeof HomeBuyersRoute
  '/investors': typeof InvestorsRoute
  '/mortgage-solutions': typeof MortgageSolutionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calculator': typeof CalculatorRoute
  '/home-buyers': typeof HomeBuyersRoute
  '/investors': typeof InvestorsRoute
  '/mortgage-solutions': typeof MortgageSolutionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/calculator'
    | '/home-buyers'
    | '/investors'
    | '/mortgage-solutions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/calculator'
    | '/home-buyers'
    | '/investors'
    | '/mortgage-solutions'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/calculator'
    | '/home-buyers'
    | '/investors'
    | '/mortgage-solutions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CalculatorRoute: typeof CalculatorRoute
  HomeBuyersRoute: typeof HomeBuyersRoute
  InvestorsRoute: typeof InvestorsRoute
  MortgageSolutionsRoute: typeof MortgageSolutionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-buyers': {
      id: '/home-buyers'
      path: '/home-buyers'
      fullPath: '/home-buyers'
      preLoaderRoute: typeof HomeBuyersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investors': {
      id: '/investors'
      path: '/investors'
      fullPath: '/investors'
      preLoaderRoute: typeof InvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mortgage-solutions': {
      id: '/mortgage-solutions'
      path: '/mortgage-solutions'
      fullPath: '/mortgage-solutions'
      preLoaderRoute: typeof MortgageSolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CalculatorRoute: CalculatorRoute,
  HomeBuyersRoute: HomeBuyersRoute,
  InvestorsRoute: InvestorsRoute,
  MortgageSolutionsRoute: MortgageSolutionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
