/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BankStatementHomeLoansRouteImport } from './routes/bank-statement-home-loans'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as CashOutRefinanceRouteImport } from './routes/cash-out-refinance'
import { Route as CompareLoanProgramsRouteImport } from './routes/compare-loan-programs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConventionalLoansRouteImport } from './routes/conventional-loans'
import { Route as DisclosuresRouteImport } from './routes/disclosures'
import { Route as FhaLoansRouteImport } from './routes/fha-loans'
import { Route as FirstTimeHomeBuyersRouteImport } from './routes/first-time-home-buyers'
import { Route as FixAndFlipFinancingRouteImport } from './routes/fix-and-flip-financing'
import { Route as HomeBuyersRouteImport } from './routes/home-buyers'
import { Route as HomeLoansRouteImport } from './routes/home-loans'
import { Route as InvestmentPropertyLoansRouteImport } from './routes/investment-property-loans'
import { Route as InvestorsRouteImport } from './routes/investors'
import { Route as ItinHomeLoansRouteImport } from './routes/itin-home-loans'
import { Route as JumboLoansRouteImport } from './routes/jumbo-loans'
import { Route as LoanProgramsRouteImport } from './routes/loan-programs'
import { Route as MortgagePreApprovalRouteImport } from './routes/mortgage-pre-approval'
import { Route as MortgageSolutionsRouteImport } from './routes/mortgage-solutions'
import { Route as MortgageToolsRouteImport } from './routes/mortgage-tools'
import { Route as NcHomeBuyerChecklistRouteImport } from './routes/nc-home-buyer-checklist'
import { Route as NonPermanentResidentMortgagesRouteImport } from './routes/non-permanent-resident-mortgages'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefinancingRouteImport } from './routes/refinancing'
import { Route as RentalPropertyFinancingRouteImport } from './routes/rental-property-financing'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as UsdaLoansRouteImport } from './routes/usda-loans'
import { Route as VaLoansRouteImport } from './routes/va-loans'
import { Route as LocationsIndexRouteImport } from './routes/locations.index'
import { Route as LocationsCityRouteImport } from './routes/locations.$city'
import { Route as ResourcesIndexRouteImport } from './routes/resources.index'
import { Route as ResourcesSlugRouteImport } from './routes/resources.$slug'
import { Route as ApiPublicLeadRouteImport } from './routes/api/public/lead'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BankStatementHomeLoansRoute = BankStatementHomeLoansRouteImport.update({
  id: '/bank-statement-home-loans',
  path: '/bank-statement-home-loans',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const CashOutRefinanceRoute = CashOutRefinanceRouteImport.update({
  id: '/cash-out-refinance',
  path: '/cash-out-refinance',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareLoanProgramsRoute = CompareLoanProgramsRouteImport.update({
  id: '/compare-loan-programs',
  path: '/compare-loan-programs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConventionalLoansRoute = ConventionalLoansRouteImport.update({
  id: '/conventional-loans',
  path: '/conventional-loans',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclosuresRoute = DisclosuresRouteImport.update({
  id: '/disclosures',
  path: '/disclosures',
  getParentRoute: () => rootRouteImport,
} as any)
const FhaLoansRoute = FhaLoansRouteImport.update({
  id: '/fha-loans',
  path: '/fha-loans',
  getParentRoute: () => rootRouteImport,
} as any)
const FirstTimeHomeBuyersRoute = FirstTimeHomeBuyersRouteImport.update({
  id: '/first-time-home-buyers',
  path: '/first-time-home-buyers',
  getParentRoute: () => rootRouteImport,
} as any)
const FixAndFlipFinancingRoute = FixAndFlipFinancingRouteImport.update({
  id: '/fix-and-flip-financing',
  path: '/fix-and-flip-financing',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeBuyersRoute = HomeBuyersRouteImport.update({
  id: '/home-buyers',
  path: '/home-buyers',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeLoansRoute = HomeLoansRouteImport.update({
  id: '/home-loans',
  path: '/home-loans',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentPropertyLoansRoute = InvestmentPropertyLoansRouteImport.update({
  id: '/investment-property-loans',
  path: '/investment-property-loans',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorsRoute = InvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => rootRouteImport,
} as any)
const ItinHomeLoansRoute = ItinHomeLoansRouteImport.update({
  id: '/itin-home-loans',
  path: '/itin-home-loans',
  getParentRoute: () => rootRouteImport,
} as any)
const JumboLoansRoute = JumboLoansRouteImport.update({
  id: '/jumbo-loans',
  path: '/jumbo-loans',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanProgramsRoute = LoanProgramsRouteImport.update({
  id: '/loan-programs',
  path: '/loan-programs',
  getParentRoute: () => rootRouteImport,
} as any)
const MortgagePreApprovalRoute = MortgagePreApprovalRouteImport.update({
  id: '/mortgage-pre-approval',
  path: '/mortgage-pre-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const MortgageSolutionsRoute = MortgageSolutionsRouteImport.update({
  id: '/mortgage-solutions',
  path: '/mortgage-solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const MortgageToolsRoute = MortgageToolsRouteImport.update({
  id: '/mortgage-tools',
  path: '/mortgage-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const NcHomeBuyerChecklistRoute = NcHomeBuyerChecklistRouteImport.update({
  id: '/nc-home-buyer-checklist',
  path: '/nc-home-buyer-checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const NonPermanentResidentMortgagesRoute =
  NonPermanentResidentMortgagesRouteImport.update({
    id: '/non-permanent-resident-mortgages',
    path: '/non-permanent-resident-mortgages',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefinancingRoute = RefinancingRouteImport.update({
  id: '/refinancing',
  path: '/refinancing',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalPropertyFinancingRoute = RentalPropertyFinancingRouteImport.update({
  id: '/rental-property-financing',
  path: '/rental-property-financing',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const UsdaLoansRoute = UsdaLoansRouteImport.update({
  id: '/usda-loans',
  path: '/usda-loans',
  getParentRoute: () => rootRouteImport,
} as any)
const VaLoansRoute = VaLoansRouteImport.update({
  id: '/va-loans',
  path: '/va-loans',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsCityRoute = LocationsCityRouteImport.update({
  id: '/locations/$city',
  path: '/locations/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/resources/$slug',
  path: '/resources/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLeadRoute = ApiPublicLeadRouteImport.update({
  id: '/api/public/lead',
  path: '/api/public/lead',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bank-statement-home-loans': typeof BankStatementHomeLoansRoute
  '/calculator': typeof CalculatorRoute
  '/cash-out-refinance': typeof CashOutRefinanceRoute
  '/compare-loan-programs': typeof CompareLoanProgramsRoute
  '/contact': typeof ContactRoute
  '/conventional-loans': typeof ConventionalLoansRoute
  '/disclosures': typeof DisclosuresRoute
  '/fha-loans': typeof FhaLoansRoute
  '/first-time-home-buyers': typeof FirstTimeHomeBuyersRoute
  '/fix-and-flip-financing': typeof FixAndFlipFinancingRoute
  '/home-buyers': typeof HomeBuyersRoute
  '/home-loans': typeof HomeLoansRoute
  '/investment-property-loans': typeof InvestmentPropertyLoansRoute
  '/investors': typeof InvestorsRoute
  '/itin-home-loans': typeof ItinHomeLoansRoute
  '/jumbo-loans': typeof JumboLoansRoute
  '/loan-programs': typeof LoanProgramsRoute
  '/mortgage-pre-approval': typeof MortgagePreApprovalRoute
  '/mortgage-solutions': typeof MortgageSolutionsRoute
  '/mortgage-tools': typeof MortgageToolsRoute
  '/nc-home-buyer-checklist': typeof NcHomeBuyerChecklistRoute
  '/non-permanent-resident-mortgages': typeof NonPermanentResidentMortgagesRoute
  '/privacy': typeof PrivacyRoute
  '/refinancing': typeof RefinancingRoute
  '/rental-property-financing': typeof RentalPropertyFinancingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/usda-loans': typeof UsdaLoansRoute
  '/va-loans': typeof VaLoansRoute
  '/locations/$city': typeof LocationsCityRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/locations/': typeof LocationsIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/api/public/lead': typeof ApiPublicLeadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bank-statement-home-loans': typeof BankStatementHomeLoansRoute
  '/calculator': typeof CalculatorRoute
  '/cash-out-refinance': typeof CashOutRefinanceRoute
  '/compare-loan-programs': typeof CompareLoanProgramsRoute
  '/contact': typeof ContactRoute
  '/conventional-loans': typeof ConventionalLoansRoute
  '/disclosures': typeof DisclosuresRoute
  '/fha-loans': typeof FhaLoansRoute
  '/first-time-home-buyers': typeof FirstTimeHomeBuyersRoute
  '/fix-and-flip-financing': typeof FixAndFlipFinancingRoute
  '/home-buyers': typeof HomeBuyersRoute
  '/home-loans': typeof HomeLoansRoute
  '/investment-property-loans': typeof InvestmentPropertyLoansRoute
  '/investors': typeof InvestorsRoute
  '/itin-home-loans': typeof ItinHomeLoansRoute
  '/jumbo-loans': typeof JumboLoansRoute
  '/loan-programs': typeof LoanProgramsRoute
  '/mortgage-pre-approval': typeof MortgagePreApprovalRoute
  '/mortgage-solutions': typeof MortgageSolutionsRoute
  '/mortgage-tools': typeof MortgageToolsRoute
  '/nc-home-buyer-checklist': typeof NcHomeBuyerChecklistRoute
  '/non-permanent-resident-mortgages': typeof NonPermanentResidentMortgagesRoute
  '/privacy': typeof PrivacyRoute
  '/refinancing': typeof RefinancingRoute
  '/rental-property-financing': typeof RentalPropertyFinancingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/usda-loans': typeof UsdaLoansRoute
  '/va-loans': typeof VaLoansRoute
  '/locations/$city': typeof LocationsCityRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/locations': typeof LocationsIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/api/public/lead': typeof ApiPublicLeadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bank-statement-home-loans': typeof BankStatementHomeLoansRoute
  '/calculator': typeof CalculatorRoute
  '/cash-out-refinance': typeof CashOutRefinanceRoute
  '/compare-loan-programs': typeof CompareLoanProgramsRoute
  '/contact': typeof ContactRoute
  '/conventional-loans': typeof ConventionalLoansRoute
  '/disclosures': typeof DisclosuresRoute
  '/fha-loans': typeof FhaLoansRoute
  '/first-time-home-buyers': typeof FirstTimeHomeBuyersRoute
  '/fix-and-flip-financing': typeof FixAndFlipFinancingRoute
  '/home-buyers': typeof HomeBuyersRoute
  '/home-loans': typeof HomeLoansRoute
  '/investment-property-loans': typeof InvestmentPropertyLoansRoute
  '/investors': typeof InvestorsRoute
  '/itin-home-loans': typeof ItinHomeLoansRoute
  '/jumbo-loans': typeof JumboLoansRoute
  '/loan-programs': typeof LoanProgramsRoute
  '/mortgage-pre-approval': typeof MortgagePreApprovalRoute
  '/mortgage-solutions': typeof MortgageSolutionsRoute
  '/mortgage-tools': typeof MortgageToolsRoute
  '/nc-home-buyer-checklist': typeof NcHomeBuyerChecklistRoute
  '/non-permanent-resident-mortgages': typeof NonPermanentResidentMortgagesRoute
  '/privacy': typeof PrivacyRoute
  '/refinancing': typeof RefinancingRoute
  '/rental-property-financing': typeof RentalPropertyFinancingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/usda-loans': typeof UsdaLoansRoute
  '/va-loans': typeof VaLoansRoute
  '/locations/$city': typeof LocationsCityRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/locations/': typeof LocationsIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/api/public/lead': typeof ApiPublicLeadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bank-statement-home-loans'
    | '/calculator'
    | '/cash-out-refinance'
    | '/compare-loan-programs'
    | '/contact'
    | '/conventional-loans'
    | '/disclosures'
    | '/fha-loans'
    | '/first-time-home-buyers'
    | '/fix-and-flip-financing'
    | '/home-buyers'
    | '/home-loans'
    | '/investment-property-loans'
    | '/investors'
    | '/itin-home-loans'
    | '/jumbo-loans'
    | '/loan-programs'
    | '/mortgage-pre-approval'
    | '/mortgage-solutions'
    | '/mortgage-tools'
    | '/nc-home-buyer-checklist'
    | '/non-permanent-resident-mortgages'
    | '/privacy'
    | '/refinancing'
    | '/rental-property-financing'
    | '/sitemap.xml'
    | '/usda-loans'
    | '/va-loans'
    | '/locations/$city'
    | '/resources/$slug'
    | '/locations/'
    | '/resources/'
    | '/api/public/lead'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bank-statement-home-loans'
    | '/calculator'
    | '/cash-out-refinance'
    | '/compare-loan-programs'
    | '/contact'
    | '/conventional-loans'
    | '/disclosures'
    | '/fha-loans'
    | '/first-time-home-buyers'
    | '/fix-and-flip-financing'
    | '/home-buyers'
    | '/home-loans'
    | '/investment-property-loans'
    | '/investors'
    | '/itin-home-loans'
    | '/jumbo-loans'
    | '/loan-programs'
    | '/mortgage-pre-approval'
    | '/mortgage-solutions'
    | '/mortgage-tools'
    | '/nc-home-buyer-checklist'
    | '/non-permanent-resident-mortgages'
    | '/privacy'
    | '/refinancing'
    | '/rental-property-financing'
    | '/sitemap.xml'
    | '/usda-loans'
    | '/va-loans'
    | '/locations/$city'
    | '/resources/$slug'
    | '/locations'
    | '/resources'
    | '/api/public/lead'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bank-statement-home-loans'
    | '/calculator'
    | '/cash-out-refinance'
    | '/compare-loan-programs'
    | '/contact'
    | '/conventional-loans'
    | '/disclosures'
    | '/fha-loans'
    | '/first-time-home-buyers'
    | '/fix-and-flip-financing'
    | '/home-buyers'
    | '/home-loans'
    | '/investment-property-loans'
    | '/investors'
    | '/itin-home-loans'
    | '/jumbo-loans'
    | '/loan-programs'
    | '/mortgage-pre-approval'
    | '/mortgage-solutions'
    | '/mortgage-tools'
    | '/nc-home-buyer-checklist'
    | '/non-permanent-resident-mortgages'
    | '/privacy'
    | '/refinancing'
    | '/rental-property-financing'
    | '/sitemap.xml'
    | '/usda-loans'
    | '/va-loans'
    | '/locations/$city'
    | '/resources/$slug'
    | '/locations/'
    | '/resources/'
    | '/api/public/lead'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BankStatementHomeLoansRoute: typeof BankStatementHomeLoansRoute
  CalculatorRoute: typeof CalculatorRoute
  CashOutRefinanceRoute: typeof CashOutRefinanceRoute
  CompareLoanProgramsRoute: typeof CompareLoanProgramsRoute
  ContactRoute: typeof ContactRoute
  ConventionalLoansRoute: typeof ConventionalLoansRoute
  DisclosuresRoute: typeof DisclosuresRoute
  FhaLoansRoute: typeof FhaLoansRoute
  FirstTimeHomeBuyersRoute: typeof FirstTimeHomeBuyersRoute
  FixAndFlipFinancingRoute: typeof FixAndFlipFinancingRoute
  HomeBuyersRoute: typeof HomeBuyersRoute
  HomeLoansRoute: typeof HomeLoansRoute
  InvestmentPropertyLoansRoute: typeof InvestmentPropertyLoansRoute
  InvestorsRoute: typeof InvestorsRoute
  ItinHomeLoansRoute: typeof ItinHomeLoansRoute
  JumboLoansRoute: typeof JumboLoansRoute
  LoanProgramsRoute: typeof LoanProgramsRoute
  MortgagePreApprovalRoute: typeof MortgagePreApprovalRoute
  MortgageSolutionsRoute: typeof MortgageSolutionsRoute
  MortgageToolsRoute: typeof MortgageToolsRoute
  NcHomeBuyerChecklistRoute: typeof NcHomeBuyerChecklistRoute
  NonPermanentResidentMortgagesRoute: typeof NonPermanentResidentMortgagesRoute
  PrivacyRoute: typeof PrivacyRoute
  RefinancingRoute: typeof RefinancingRoute
  RentalPropertyFinancingRoute: typeof RentalPropertyFinancingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UsdaLoansRoute: typeof UsdaLoansRoute
  VaLoansRoute: typeof VaLoansRoute
  LocationsCityRoute: typeof LocationsCityRoute
  ResourcesSlugRoute: typeof ResourcesSlugRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
  ApiPublicLeadRoute: typeof ApiPublicLeadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank-statement-home-loans': {
      id: '/bank-statement-home-loans'
      path: '/bank-statement-home-loans'
      fullPath: '/bank-statement-home-loans'
      preLoaderRoute: typeof BankStatementHomeLoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash-out-refinance': {
      id: '/cash-out-refinance'
      path: '/cash-out-refinance'
      fullPath: '/cash-out-refinance'
      preLoaderRoute: typeof CashOutRefinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare-loan-programs': {
      id: '/compare-loan-programs'
      path: '/compare-loan-programs'
      fullPath: '/compare-loan-programs'
      preLoaderRoute: typeof CompareLoanProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conventional-loans': {
      id: '/conventional-loans'
      path: '/conventional-loans'
      fullPath: '/conventional-loans'
      preLoaderRoute: typeof ConventionalLoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclosures': {
      id: '/disclosures'
      path: '/disclosures'
      fullPath: '/disclosures'
      preLoaderRoute: typeof DisclosuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fha-loans': {
      id: '/fha-loans'
      path: '/fha-loans'
      fullPath: '/fha-loans'
      preLoaderRoute: typeof FhaLoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/first-time-home-buyers': {
      id: '/first-time-home-buyers'
      path: '/first-time-home-buyers'
      fullPath: '/first-time-home-buyers'
      preLoaderRoute: typeof FirstTimeHomeBuyersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fix-and-flip-financing': {
      id: '/fix-and-flip-financing'
      path: '/fix-and-flip-financing'
      fullPath: '/fix-and-flip-financing'
      preLoaderRoute: typeof FixAndFlipFinancingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-buyers': {
      id: '/home-buyers'
      path: '/home-buyers'
      fullPath: '/home-buyers'
      preLoaderRoute: typeof HomeBuyersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-loans': {
      id: '/home-loans'
      path: '/home-loans'
      fullPath: '/home-loans'
      preLoaderRoute: typeof HomeLoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investment-property-loans': {
      id: '/investment-property-loans'
      path: '/investment-property-loans'
      fullPath: '/investment-property-loans'
      preLoaderRoute: typeof InvestmentPropertyLoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investors': {
      id: '/investors'
      path: '/investors'
      fullPath: '/investors'
      preLoaderRoute: typeof InvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itin-home-loans': {
      id: '/itin-home-loans'
      path: '/itin-home-loans'
      fullPath: '/itin-home-loans'
      preLoaderRoute: typeof ItinHomeLoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jumbo-loans': {
      id: '/jumbo-loans'
      path: '/jumbo-loans'
      fullPath: '/jumbo-loans'
      preLoaderRoute: typeof JumboLoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan-programs': {
      id: '/loan-programs'
      path: '/loan-programs'
      fullPath: '/loan-programs'
      preLoaderRoute: typeof LoanProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mortgage-pre-approval': {
      id: '/mortgage-pre-approval'
      path: '/mortgage-pre-approval'
      fullPath: '/mortgage-pre-approval'
      preLoaderRoute: typeof MortgagePreApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mortgage-solutions': {
      id: '/mortgage-solutions'
      path: '/mortgage-solutions'
      fullPath: '/mortgage-solutions'
      preLoaderRoute: typeof MortgageSolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mortgage-tools': {
      id: '/mortgage-tools'
      path: '/mortgage-tools'
      fullPath: '/mortgage-tools'
      preLoaderRoute: typeof MortgageToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nc-home-buyer-checklist': {
      id: '/nc-home-buyer-checklist'
      path: '/nc-home-buyer-checklist'
      fullPath: '/nc-home-buyer-checklist'
      preLoaderRoute: typeof NcHomeBuyerChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/non-permanent-resident-mortgages': {
      id: '/non-permanent-resident-mortgages'
      path: '/non-permanent-resident-mortgages'
      fullPath: '/non-permanent-resident-mortgages'
      preLoaderRoute: typeof NonPermanentResidentMortgagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refinancing': {
      id: '/refinancing'
      path: '/refinancing'
      fullPath: '/refinancing'
      preLoaderRoute: typeof RefinancingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rental-property-financing': {
      id: '/rental-property-financing'
      path: '/rental-property-financing'
      fullPath: '/rental-property-financing'
      preLoaderRoute: typeof RentalPropertyFinancingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usda-loans': {
      id: '/usda-loans'
      path: '/usda-loans'
      fullPath: '/usda-loans'
      preLoaderRoute: typeof UsdaLoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/va-loans': {
      id: '/va-loans'
      path: '/va-loans'
      fullPath: '/va-loans'
      preLoaderRoute: typeof VaLoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/': {
      id: '/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$city': {
      id: '/locations/$city'
      path: '/locations/$city'
      fullPath: '/locations/$city'
      preLoaderRoute: typeof LocationsCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$slug': {
      id: '/resources/$slug'
      path: '/resources/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lead': {
      id: '/api/public/lead'
      path: '/api/public/lead'
      fullPath: '/api/public/lead'
      preLoaderRoute: typeof ApiPublicLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BankStatementHomeLoansRoute: BankStatementHomeLoansRoute,
  CalculatorRoute: CalculatorRoute,
  CashOutRefinanceRoute: CashOutRefinanceRoute,
  CompareLoanProgramsRoute: CompareLoanProgramsRoute,
  ContactRoute: ContactRoute,
  ConventionalLoansRoute: ConventionalLoansRoute,
  DisclosuresRoute: DisclosuresRoute,
  FhaLoansRoute: FhaLoansRoute,
  FirstTimeHomeBuyersRoute: FirstTimeHomeBuyersRoute,
  FixAndFlipFinancingRoute: FixAndFlipFinancingRoute,
  HomeBuyersRoute: HomeBuyersRoute,
  HomeLoansRoute: HomeLoansRoute,
  InvestmentPropertyLoansRoute: InvestmentPropertyLoansRoute,
  InvestorsRoute: InvestorsRoute,
  ItinHomeLoansRoute: ItinHomeLoansRoute,
  JumboLoansRoute: JumboLoansRoute,
  LoanProgramsRoute: LoanProgramsRoute,
  MortgagePreApprovalRoute: MortgagePreApprovalRoute,
  MortgageSolutionsRoute: MortgageSolutionsRoute,
  MortgageToolsRoute: MortgageToolsRoute,
  NcHomeBuyerChecklistRoute: NcHomeBuyerChecklistRoute,
  NonPermanentResidentMortgagesRoute: NonPermanentResidentMortgagesRoute,
  PrivacyRoute: PrivacyRoute,
  RefinancingRoute: RefinancingRoute,
  RentalPropertyFinancingRoute: RentalPropertyFinancingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UsdaLoansRoute: UsdaLoansRoute,
  VaLoansRoute: VaLoansRoute,
  LocationsCityRoute: LocationsCityRoute,
  ResourcesSlugRoute: ResourcesSlugRoute,
  LocationsIndexRoute: LocationsIndexRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
  ApiPublicLeadRoute: ApiPublicLeadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
